(lang dune 3.20)

(name par-samples)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name par-samples)
 (allow_empty)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends
 ocaml
 (ocamlformat (= 0.26.2+ox)))
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
